### PR TITLE
User list review

### PR DESCRIPTION
**Pull request by warlof**
Gmail like :
Add a swipe quick actions on the user list. Swipe left on a item list display quick actions buttons. Swipe right hide it.

### CODE REVIEW

**Comment by fwoelffel** [comment]
Have you tested this on ios/safari ? Natively, a "swipe left" gesture brings you to the previous page.

**Comment by warlof** [comment]
Don't have an iphone in order to test that =/
I will try to work on that.

**Comment by warlof** [comment]
I suppose that swipe-right is used for the next page ?

**Comment by corentindesfarges** [comment]
Moreover, I don't think it is a good idea to use this kind of quick actions. Mainly to avoid bad movements.

**Pull request closed without merging**
